# 需要额外建一个 test.yml

name: build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_call:

env:
  # https://stackoverflow.com/a/75486166
  CI: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7.29.0
      - uses: actions/setup-node@v3
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        with:
          node-version: 16
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile --prefer-offline
      - run: pnpm build
      - run: zip -r @zimi.zip @zimi
      # store build assets
      - uses: actions/upload-artifact@master
        with:
          name: build assets
          path: '@zimi.zip'
