name: Production deploy
on:
  push:
    tags:
      - '*'
env:
  # https://stackoverflow.com/a/75486166
  CI: true

jobs:
  release:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Install deps
        uses: pnpm/action-setup@v2
        with:
          version: 7.29.0
          run_install: |
            - recursive: true
              args: [--no-frozen-lockfile]

      - name: Build
        run: pnpm run build

      - name: Create release pull request
        id: changesets
        uses: changesets/action@v1
        with:
          commit: "chore: update to $GITHUB_REF_NAME"
          title: "chore: update to $GITHUB_REF_NAME"
          publish: pnpm publish --no-git-checks --access public -r
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge pull request
        id: merge_request
        if: steps.changesets.outputs.pullRequestNumber > 0
        uses: actions/github-script@v6
        with:
          script: |
            const owner = "$GITHUB_REPOSITORY_OWNER";
            const repo = "${{ github.event.repository.name }}";
            const pull_number = "${{ steps.changesets.outputs.pullRequestNumber }}";
            await github.rest.pulls.merge({ owner, repo, pull_number, merge_method: "squash"});
            return true;

