name: Production deploy
on:
  push:
    branches:
      - 'release/*'

env:
  # https://stackoverflow.com/a/75486166
  CI: true
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    uses: './.github/workflows/build.yml'
  release:
    timeout-minutes: 15
    needs: build
    runs-on: ubuntu-latest
    steps:
      # install deps
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7.29.0
      - uses: actions/setup-node@v3
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        with:
          node-version: 16
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile --prefer-offline

      # download build assets
      - uses: actions/download-artifact@master
        with:
          name: build assets
          path: '@zimi.zip'
      - run: chmod 777 ./@zimi.zip
      - run: ls -lah
      - run: unzip ./@zimi.zip -d @zimi
      - run: rm ./@zimi.zip

      - name: Create release pull request
        id: changesets
        uses: changesets/action@v1
        with:
          commit: 'feat: update version'
          title: 'feat: update version'
          version: pnpm changeset version
          publish: pnpm publish --no-git-checks --access public -r

      - name: Merge pull request
        id: merge_request
        if: ${{ steps.changesets.outputs.pullRequestNumber > 0 }}
        uses: actions/github-script@v6
        with:
          script: |
            const owner = process.env.GITHUB_REPOSITORY_OWNER;
            const repo = "${{ github.event.repository.name }}";
            const pull_number = "${{ steps.changesets.outputs.pullRequestNumber }}";
            await github.rest.pulls.merge({ owner, repo, pull_number, merge_method: "squash"});
            return true;
