# 需要额外建一个 test.yml

name: test
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_call:

env:
  # https://stackoverflow.com/a/75486166
  CI: true
  HUSKY: 0

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7.29.0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'
          # Please note that you need to set the registry-url to https://registry.npmjs.org/ in setup-node to properly configure your credentials.
          registry-url: 'https://registry.npmjs.org'
      - run: pnpm install --frozen-lockfile --prefer-offline
      - run: pnpm test
